-- Deploy all PostgreSQL schema objects for the Artsy template.
-- This file is auto-generated by gulpfile.js in the Artsy.SQL project.
-- Run this script against a default database (e.g., template1); it creates the application database if it does not exist.

SELECT 'CREATE DATABASE artsy' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'artsy')
\gexec
\connect artsy

-- Tables
\i Tables/AppRoles.sql
\i Tables/AppUsers.sql
\i Tables/AppUserRoles.sql
\i Tables/AppUserTokens.sql
\i Tables/ImageGeneration.sql
\i Tables/LLM_Models.sql
\i Tables/Printify/PrintifyBlueprintPrintProviders.sql
\i Tables/Printify/PrintifyBlueprintShipping.sql
\i Tables/Printify/PrintifyBlueprintVariantPlaceholders.sql
\i Tables/Printify/PrintifyBlueprintVariants.sql
\i Tables/Printify/PrintifyBlueprints.sql
\i Tables/Printify/PrintifyBlueprintImages.sql
\i Tables/Projects/Projects.sql
\i Tables/Projects/ProjectBlueprints.sql
\i Tables/Projects/ProjectCollections.sql
\i Tables/Projects/ProjectCollectionProductImages.sql
\i Tables/Projects/ProjectItems.sql
\i Tables/Projects/ProjectCollectionAnswers.sql
\i Tables/Projects/ProjectCollectionArtwork.sql
\i Tables/Projects/ProjectCollectionChatHistory.sql
\i Tables/Projects/ProjectImageGenerations.sql
\i Tables/Projects/ProjectImageUpscales.sql
\i Tables/Projects/ProjectItemArtwork.sql
\i Tables/Projects/ProjectItemPreviews.sql
\i Tables/Projects/ProjectItemQuestions.sql
\i Tables/Projects/ProjectItemReferences.sql
\i Tables/Projects/ProjectQuestions.sql
\i Tables/Trends.sql

-- Sequences
\i Sequences/SequenceAppRoles.sql
\i Sequences/SequenceAppUserTokens.sql

-- Indexes
\i Indexes/IndexAppUsersEmail.sql

-- Functions
\i Functions/ResetSequences.sql

-- SeedData
\i SeedData/AppRoles.sql
