-- Deploy all PostgreSQL schema objects for the Artsy template.
-- This file is auto-generated by gulpfile.js in the Artsy.SQL project.
-- Run this script against a default database (e.g., template1); it creates the application database if it does not exist.

SELECT 'CREATE DATABASE artsy' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'artsy')
\gexec
\connect artsy

-- Tables
\i Tables/Auth/AppRoles.sql
\i Tables/Auth/AppUsers.sql
\i Tables/AppUserInstagramAccounts.sql
\i Tables/Auth/AppUserRoles.sql
\i Tables/Auth/AppUserTokens.sql
\i Tables/Billing/Products.sql
\i Tables/Billing/Subscriptions.sql
\i Tables/Billing/AppUserSubscriptions.sql
\i Tables/Billing/Invoices.sql
\i Tables/Billing/AppUserAITokens.sql
\i Tables/CustomImages.sql
\i Tables/ImageGeneration.sql
\i Tables/LLM_Models.sql
\i Tables/Orders/HangfireOrders.sql
\i Tables/Orders/Orders.sql
\i Tables/Orders/OrderItems.sql
\i Tables/Orders/OrderShipments.sql
\i Tables/Printify/PrintifyBlueprintPrintProviders.sql
\i Tables/Printify/PrintifyBlueprintShipping.sql
\i Tables/Printify/PrintifyBlueprintVariantPlaceholders.sql
\i Tables/Printify/PrintifyBlueprintVariants.sql
\i Tables/Printify/PrintifyBlueprints.sql
\i Tables/Printify/PrintifyBlueprintImages.sql
\i Tables/Printify/PrintifyBlueprintImageVariants.sql
\i Tables/Projects/Projects.sql
\i Tables/Projects/ProjectBlueprints.sql
\i Tables/Projects/ProjectBlueprintProductImages.sql
\i Tables/Projects/ProjectCollections.sql
\i Tables/Projects/ProjectCollectionInstagramPosts.sql
\i Tables/Projects/ProjectCollectionProductImages.sql
\i Tables/Projects/ProjectCollectionProducts.sql
\i Tables/Projects/ProjectCollectionPrintifyProducts.sql
\i Tables/Projects/ProjectCollectionPrintifyProductMockups.sql
\i Tables/Projects/ProjectCollectionProductVariants.sql
\i Tables/Projects/ProjectIdeas.sql
\i Tables/Projects/ProjectIdeaVariations.sql
\i Tables/Projects/ProjectItems.sql
\i Tables/Projects/ProjectCollectionAnswers.sql
\i Tables/Projects/ProjectCollectionArtwork.sql
\i Tables/Projects/ProjectCollectionChatHistory.sql
\i Tables/Projects/ProjectCollectionInstagramPostImages.sql
\i Tables/Projects/ProjectCollectionProductPlacements.sql
\i Tables/Projects/ProjectImageGenerations.sql
\i Tables/Projects/ProjectImageUpscales.sql
\i Tables/Projects/ProjectItemArtwork.sql
\i Tables/Projects/ProjectItemPreviews.sql
\i Tables/Projects/ProjectItemQuestions.sql
\i Tables/Projects/ProjectItemReferences.sql
\i Tables/Projects/ProjectQuestions.sql
\i Tables/Trends.sql

-- Sequences
\i Sequences/SequenceAppRoles.sql
\i Sequences/SequenceAppUserTokens.sql

-- Indexes
\i Indexes/IndexAppUsersEmail.sql

-- Functions
\i Functions/ResetSequences.sql

-- SeedData
\i SeedData/AppRoles.sql
