import { Api } from '@/api/Api';

const Projects = (args) => Api({ ...args }).endpoints(({ api }) => {
  const apiPath = '/api/projects';
  return {
    getAll: () => api.get(`${apiPath}/get-all`),
    getArchived: () => api.get(`${apiPath}/get-archived`),
    archiveProject: (request) => api.post(`${apiPath}/archive-project`, request),
    unarchiveProject: (request) => api.post(`${apiPath}/unarchive-project`, request),
    getById: (id) => api.get(`${apiPath}/get-by-id?id=${id}`),
    getCollections: (projectId) => api.get(`${apiPath}/get-collections?projectId=${projectId}`),
    deleteCollection: (request) => api.post(`${apiPath}/delete-collection`, request),
    updateCollectionTitle: (request) => api.post(`${apiPath}/update-collection-title`, request),
    getItems: (projectId) => api.get(`${apiPath}/get-items?projectId=${projectId}`),
    createItem: (request) => api.post(`${apiPath}/create-item`, request),
    deleteItem: (request) => api.post(`${apiPath}/delete-item`, request),
    reorderItems: (request) => api.post(`${apiPath}/reorder-items`, request),
    getBlueprints: (projectId) => api.get(`${apiPath}/get-blueprints?projectId=${projectId}`),
    getBlueprintsList: (projectId) => api.get(`${apiPath}/get-blueprints-list?projectId=${projectId}`),
    createBlueprint: (request) => api.post(`${apiPath}/create-blueprint`, request),
    deleteBlueprint: (request) => api.post(`${apiPath}/delete-blueprint`, request),
    updateBlueprint: (request) => api.post(`${apiPath}/update-blueprint`, request),
    updateBlueprintVariants: (request) => api.post(`${apiPath}/update-blueprint-variants`, request),
    updateBlueprintPricing: (request) => api.post(`${apiPath}/update-blueprint-pricing`, request),
    updateBlueprintDetails: (request) => api.post(`${apiPath}/update-blueprint-details`, request),
    generateBlueprintInfo: (request) => api.post(`${apiPath}/generate-blueprint-info`, request),
    updateBlueprintProductImagePrompt: (request) => api.post(`${apiPath}/update-product-blueprint-image`, request),
    getBlueprintPlaceholders: (projectId) => api.get(`${apiPath}/get-blueprint-placeholders?projectId=${projectId}`),
    updateBlueprintPlacement: (request) => api.post(`${apiPath}/update-blueprint-placement`, request),
    updateItemTitle: (request) => api.post(`${apiPath}/update-item-title`, request),
    updateItemSocialMedia: (request) => api.post(`${apiPath}/update-item-social-media`, request),
    getItemArtwork: (itemId) => api.get(`${apiPath}/get-item-artwork?itemId=${itemId}`),
    updateItemPrompt: (request) => api.post(`${apiPath}/update-item-prompt`, request),
    updateItemImageModel: (request) => api.post(`${apiPath}/update-item-image-model`, request),
    estimateItemTokens: (itemId, modelId = '', collectionId = '', design = '') => api.get(`${apiPath}/estimate-item-tokens?itemId=${itemId}&modelId=${modelId || ''}${collectionId ? `&collectionId=${collectionId}` : ''}${design ? `&design=${design}` : ''}`),
    updateItemArtworkType: (request) => api.post(`${apiPath}/update-item-artwork-type`, request),
    updateItemAspectRatio: (request) => api.post(`${apiPath}/update-item-aspect-ratio`, request),
    updateItemIgnoredQuestions: (request) => api.post(`${apiPath}/update-item-ignored-questions`, request),
    updateItemOpacity: (request) => api.post(`${apiPath}/update-item-opacity`, request),
    getItemPreviews: (itemId) => api.get(`${apiPath}/get-item-previews?itemId=${itemId}`),
    generateItemPreview: (request) => api.post(`${apiPath}/generate-item-preview`, request),
    deleteItemPreview: (request) => api.post(`${apiPath}/delete-item-preview`, request),
    getItemPreviewUrl: (itemId, previewId, thumb = false) => `${apiPath}/item/${itemId}/preview/${previewId}${thumb ? '?thumb=true' : ''}`,
    getItemReferences: (itemId) => api.get(`${apiPath}/get-item-references?itemId=${itemId}`),
    getAllItemReferences: (projectId) => api.get(`${apiPath}/get-all-item-references?projectId=${projectId}`),
    uploadItemReference: (itemId, file) => {
      const formData = new FormData();
      formData.append('file', file);
      formData.append('itemId', itemId);
      return api.post(`${apiPath}/upload-item-reference`, formData, { headers: { 'Content-Type': 'multipart/form-data' } });
    },
    deleteItemReference: (request) => api.post(`${apiPath}/delete-item-reference`, request),
    addArtworkReference: (request) => api.post(`${apiPath}/add-artwork-reference`, request),
    addCustomImageReference: (request) => api.post(`${apiPath}/add-custom-image-reference`, request),
    getItemReferenceUrl: (itemId, referenceId, thumb = false) => `${apiPath}/item/${itemId}/reference/${referenceId}${thumb ? '?thumb=true' : ''}`,
    getItemQuestions: (itemId) => api.get(`${apiPath}/get-item-questions?itemId=${itemId}`),
    createItemQuestion: (request) => api.post(`${apiPath}/create-item-question`, request),
    updateItemQuestion: (request) => api.post(`${apiPath}/update-item-question`, request),
    deleteItemQuestion: (request) => api.post(`${apiPath}/delete-item-question`, request),
    getQuestions: (projectId) => api.get(`${apiPath}/get-questions?projectId=${projectId}`),
    getChecklist: (projectId) => api.get(`${apiPath}/get-checklist?projectId=${projectId}`),
    createQuestion: (request) => api.post(`${apiPath}/create-question`, request),
    updateQuestion: (request) => api.post(`${apiPath}/update-question`, request),
    deleteQuestion: (request) => api.post(`${apiPath}/delete-question`, request),
    getArtwork: (projectId, options = {}) => {
      const params = new URLSearchParams({ projectId });
      if (options.collectionId) params.append('collectionId', options.collectionId);
      if (typeof options.start === 'number') params.append('start', options.start);
      if (typeof options.length === 'number') params.append('length', options.length);
      return api.get(`${apiPath}/get-artwork?${params.toString()}`);
    },
    getCollectionArtworkUrl: (collectionId, artworkId, index) => `${apiPath}/collection/${collectionId}/artwork/${artworkId}/${index}`,
    create: (project) => api.post(`${apiPath}/create`, project),
    updateTitle: (request) => api.post(`${apiPath}/update-title`, request),
    updateKey: (request) => api.post(`${apiPath}/update-key`, request),
    updatePublishToPrintify: (request) => api.post(`${apiPath}/update-publish-to-printify`, request),
    updateInstagramId: (request) => api.post(`${apiPath}/update-instagram-id`, request),
    updatePostToInstagram: (request) => api.post(`${apiPath}/update-post-to-instagram`, request),
    getPrintifyShops: () => api.get(`${apiPath}/get-printify-shops`),
    createCollection: (request) => api.post(`${apiPath}/create-collection`, request),
    getCollectionAnswers: (collectionId) => api.get(`${apiPath}/get-collection-answers?collectionId=${collectionId}`),
    getCollectionArtwork: (collectionId) => api.get(`${apiPath}/get-collection-artwork?collectionId=${collectionId}`),
    saveCollectionDraft: (request) => api.post(`${apiPath}/save-collection-draft`, request),
    generateCollectionArtwork: (request) => api.post(`${apiPath}/generate-collection-artwork`, request),
    fixSeamlessPlacements: (request) => api.post(`${apiPath}/fix-seamless-placements`, request),
    upscaleArtwork: (request) => api.post(`${apiPath}/upscale-artwork`, request),
    acceptCollectionArtwork: (request) => api.post(`${apiPath}/accept-collection-artwork`, request),
    autoAcceptCustomArtwork: (request) => api.post(`${apiPath}/auto-accept-custom-artwork`, request),
    deleteCollectionArtwork: (request) => api.post(`${apiPath}/delete-collection-artwork`, request),
    deleteProductImage: (request) => api.post(`${apiPath}/delete-product-image`, request),
    deactivateProductImages: (request) => api.post(`${apiPath}/deactivate-product-images`, request),
    syncProductImageSelections: (request) => api.post(`${apiPath}/sync-product-image-selections`, request),
    estimateCollectionTokens: (request) => api.post(`${apiPath}/estimate-collection-tokens`, request),
    generateArtworkThumbnail: (request) => api.post(`${apiPath}/generate-artwork-thumbnail`, request),
    getProductImageVariants: (projectId, collectionId) => api.get(`${apiPath}/get-product-image-variants?projectId=${projectId}&collectionId=${collectionId}`),
    estimateProductImageTokens: (request) => api.post(`${apiPath}/estimate-product-image-tokens`, request),
    generateProductImage: (request) => api.post(`${apiPath}/generate-product-image`, request),
    acceptProductImage: (request) => api.post(`${apiPath}/accept-product-image`, request),
    getProductImages: (collectionId) => api.get(`${apiPath}/collection/${collectionId}/product-images`),
    updateCollectionProductsActive: (request) => api.post(`${apiPath}/update-collection-products-active`, request),
    saveCollectionProducts: (request) => api.post(`${apiPath}/save-collection-products`, request),
    getCollectionProducts: (collectionId) => api.get(`${apiPath}/get-collection-products?collectionId=${collectionId}`),
    updateCollectionProductName: (request) => api.post(`${apiPath}/update-collection-product-name`, request),
    getCollectionProductDetails: (collectionId, projectBlueprintId) => api.get(`${apiPath}/get-collection-product-details?collectionId=${collectionId}&projectBlueprintId=${projectBlueprintId}`),
    updateCollectionProductDetails: (request) => api.post(`${apiPath}/update-collection-product-details`, request),
    generateCollectionProductInfo: (request) => api.post(`${apiPath}/generate-collection-product-info`, request),
    getProductBlueprintImages: (projectBlueprintId) => api.get(`${apiPath}/get-product-blueprint-images?projectBlueprintId=${projectBlueprintId}`),
    getAllProductBlueprintImages: (projectId) => api.get(`${apiPath}/get-all-product-blueprint-images?projectId=${projectId}`),
    createProductBlueprintImage: (request) => api.post(`${apiPath}/create-product-blueprint-image`, request),
    updateProductBlueprintImage: (request) => api.post(`${apiPath}/update-product-blueprint-image`, request),
    deleteProductBlueprintImage: (request) => api.post(`${apiPath}/delete-product-blueprint-image`, request),
    getPlacementGroups: (projectId, blueprintId) => api.get(`${apiPath}/get-placement-groups?projectId=${projectId}&blueprintId=${blueprintId}`),
    createPlacementGroup: (request) => api.post(`${apiPath}/create-placement-group`, request),
    deletePlacementGroup: (request) => api.post(`${apiPath}/delete-placement-group`, request),
    savePlacementGroupImage: (request) => api.post(`${apiPath}/save-placement-group-image`, request),
    deletePlacementGroupImage: (request) => api.post(`${apiPath}/delete-placement-group-image`, request),
    updateSocialMediaConfig: (request) => api.post(`${apiPath}/update-social-media-config`, request),
    generateSocialMediaDescription: (request) => api.post(`${apiPath}/generate-social-media-description`, request),
    postToSocialMedia: (request) => api.post('/api/instagram/post-to-social-media', request),
    publishPrintifyProduct: (request) => api.post('/api/printify-products/publish', request),
    unpublishPrintifyProduct: (request) => api.post('/api/printify-products/unpublish', request),
    getIdeas: (projectId) => api.get(`${apiPath}/${projectId}/ideas`),
    getIdea: (projectId, ideaId) => api.get(`${apiPath}/${projectId}/ideas/${ideaId}`),
    createIdea: (projectId, request) => api.post(`${apiPath}/${projectId}/ideas/create-idea`, request),
    createIdeaVariation: (projectId, ideaId) => api.post(`${apiPath}/${projectId}/ideas/${ideaId}/variations`),
    deleteIdea: (projectId, ideaId) => api.delete(`${apiPath}/${projectId}/ideas/${ideaId}`),
    makeIdeaCollection: (projectId, ideaId, request) => api.post(`${apiPath}/${projectId}/ideas/${ideaId}/collection`, request),
    getCollectionArtworkReferences: (collectionId, itemId) => api.get(`${apiPath}/get-collection-artwork-references?collectionId=${collectionId}&itemId=${itemId}`),
    addCollectionArtworkReference: (request) => api.post(`${apiPath}/add-collection-artwork-reference`, request),
    deleteCollectionArtworkReference: (request) => api.post(`${apiPath}/delete-collection-artwork-reference`, request),

  };
});

export { Projects };
