CREATE TABLE IF NOT EXISTS public."ImageGeneration"
(
    "Id" SERIAL PRIMARY KEY,
    "ModelKey" VARCHAR(64) NOT NULL,
    "Name" VARCHAR(128) NOT NULL,
    "Model" VARCHAR(128) NOT NULL,
    "CPMITTokens" DECIMAL(18,6) NOT NULL DEFAULT 0,
    "CPMIITokens" DECIMAL(18,6) NOT NULL DEFAULT 0,
    "CPMOTokens" DECIMAL(18,6) NOT NULL DEFAULT 0,
    "Active" BOOLEAN NOT NULL DEFAULT TRUE,
    "TokenConversion" DECIMAL(18,6) NOT NULL DEFAULT 10,
    "DateCreated" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DateUpdated" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE public."ImageGeneration" ADD COLUMN IF NOT EXISTS "Active" BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE public."ImageGeneration" ADD COLUMN IF NOT EXISTS "TokenConversion" DECIMAL(18,6) NOT NULL DEFAULT 10;