CREATE TABLE IF NOT EXISTS public."ImageGeneration"
(
    "Id" SERIAL PRIMARY KEY,
    "ModelKey" VARCHAR(64) NOT NULL,
    "Name" VARCHAR(128) NOT NULL,
    "Model" VARCHAR(128) NOT NULL,
    "Type" INT NOT NULL DEFAULT 0,
    "CPMITTokens" DECIMAL(18,6) NOT NULL DEFAULT 0,
    "CPMIITokens" DECIMAL(18,6) NOT NULL DEFAULT 0,
    "CPMOTokens" DECIMAL(18,6) NOT NULL DEFAULT 0,
    "CP1K" DECIMAL(18,6) NOT NULL DEFAULT 0,
    "CP2K" DECIMAL(18,6) NOT NULL DEFAULT 0,
    "CP4K" DECIMAL(18,6) NOT NULL DEFAULT 0,
    "CP8K" DECIMAL(18,6) NOT NULL DEFAULT 0,
    "Active" BOOLEAN NOT NULL DEFAULT TRUE,
    "DateCreated" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "DateUpdated" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE public."ImageGeneration" ADD COLUMN IF NOT EXISTS "Active" BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE public."ImageGeneration" ADD COLUMN IF NOT EXISTS "Type" INT NOT NULL DEFAULT 0;
ALTER TABLE public."ImageGeneration" ADD COLUMN IF NOT EXISTS "CP1K" DECIMAL(18,6) NOT NULL DEFAULT 0;
ALTER TABLE public."ImageGeneration" ADD COLUMN IF NOT EXISTS "CP2K" DECIMAL(18,6) NOT NULL DEFAULT 0;
ALTER TABLE public."ImageGeneration" ADD COLUMN IF NOT EXISTS "CP4K" DECIMAL(18,6) NOT NULL DEFAULT 0;
ALTER TABLE public."ImageGeneration" ADD COLUMN IF NOT EXISTS "CP8K" DECIMAL(18,6) NOT NULL DEFAULT 0;