CREATE TABLE IF NOT EXISTS public."Products"
(
    "Id" SERIAL PRIMARY KEY,
    "Title" VARCHAR(64) NOT NULL,
    "Price" INT NOT NULL DEFAULT 0,
    "Tokens" INT NOT NULL DEFAULT 0,
    "Archived" BOOLEAN NOT NULL DEFAULT FALSE,
    "DateCreated" TIMESTAMP NOT NULL DEFAULT NOW()
);

ALTER TABLE public."Products" ADD COLUMN IF NOT EXISTS "Archived" BOOLEAN NOT NULL DEFAULT FALSE;
